[package]
name = "create-leptos-csr-tw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.11.0"
fs_extra = "1.3.0"
regex = "1.10.2"
reqwest = "0.11.22"
url = "2.4.1"
